# Adapted from: https://docs.python.org/3/reference/grammar.html and the Lark Python grammar

input: (_NEWLINE | stmt)*

?literal: number | string | boolean
reference: name ("." name)*

?stmt: simple_stmt | compound_stmt
?simple_stmt: small_stmt (";" small_stmt)* [";"] _NEWLINE
?small_stmt: (func_call | typed_assign | assign | pass_stmt )
?compound_stmt: if_stmt
pass_stmt: "pass"



# assignment

# can currently only assign constant values to vars
?type_name: reference
typed_assign: name ":" type_name "=" assign_value
assign: name "=" assign_value
?assign_value: literal
             | reference # can only be a ref to enum const



# branching

if_stmt: "if" condition ":" suite elifs ["else" ":" suite]
elifs: elif_*
elif_: "elif" condition ":" suite
suite: simple_stmt | _NEWLINE _INDENT stmt+ _DEDENT
condition: test


# logical tests

?test: or_test
?or_test: and_test ("or" and_test)*
?and_test: not_test_ ("and" not_test_)*
?not_test_: "not" not_test_ -> not_test
          | comparison
?comparison: argument [comp_op argument]
comp_op: COMPARISON_OP



# function calling

?func_name: reference
func_call: func_name "(" [arguments] ")"
arguments: argument ("," argument)*
?argument: func_call
         | reference # can only be enum const
         | literal



# not used in grammar, but may appear in "node" passed from Parser to Compiler
encoding_decl: name

number: DEC_NUMBER | HEX_NUMBER | BIN_NUMBER | OCT_NUMBER | FLOAT_NUMBER | IMAG_NUMBER
string: STRING | LONG_STRING
boolean: CONST_FALSE | CONST_TRUE

# Other terminals

_NEWLINE: ( /\r?\n[\t ]*/ | COMMENT )+

%ignore /[\t \f]+/  // WS
%ignore /\\[\t \f]*\r?\n/   // LINE_CONT
%ignore COMMENT
%declare _INDENT _DEDENT


# Python terminals

!name: NAME
NAME: /[^\W\d]\w*/
COMMENT: /#[^\n]*/
CONST_TRUE: "True"
CONST_FALSE: "False"
COMPARISON_OP: ">" | "<" | "<=" | ">=" | "==" | "!="

STRING: /([ubf]?r?|r[ubf])("(?!"").*?(?<!\\)(\\\\)*?"|'(?!'').*?(?<!\\)(\\\\)*?')/i
LONG_STRING: /([ubf]?r?|r[ubf])(""".*?(?<!\\)(\\\\)*?"""|'''.*?(?<!\\)(\\\\)*?''')/is

_SPECIAL_DEC: "0".."9"        ("_"?  "0".."9"                       )*
DEC_NUMBER:   "1".."9"        ("_"?  "0".."9"                       )*
          |   "0"             ("_"?  "0"                            )* /(?![1-9])/
HEX_NUMBER.2: "0" ("x" | "X") ("_"? ("0".."9" | "a".."f" | "A".."F"))+
OCT_NUMBER.2: "0" ("o" | "O") ("_"?  "0".."7"                       )+
BIN_NUMBER.2: "0" ("b" | "B") ("_"?  "0".."1"                       )+

_EXP: ("e"|"E") ["+" | "-"] _SPECIAL_DEC
DECIMAL: "." _SPECIAL_DEC | _SPECIAL_DEC "." _SPECIAL_DEC?
FLOAT_NUMBER.2: _SPECIAL_DEC _EXP | DECIMAL _EXP?
IMAG_NUMBER.2: (_SPECIAL_DEC      | FLOAT_NUMBER) ("J" | "j")