# Adapted from: https://docs.python.org/3/reference/grammar.html and the Lark Python grammar

input: (_NEWLINE | _stmt)*

_literal: number | string | boolean
reference: name ("." name)*

_stmt: _small_stmt _NEWLINE | _compound_stmt
_small_stmt: (func_call | assign | pass_stmt )
_compound_stmt: if_stmt
pass_stmt: "pass"



# assignment

# can currently only assign constant values to vars
assign: name [":" reference] "=" _expr



# branching

if_stmt: "if" _expr ":" body elifs ["else" ":" body]
elifs: elif_*
elif_: "elif" _expr ":" body
body: _NEWLINE _INDENT _stmt+ _DEDENT

_expr: _test

# logical tests
_test: or_test
?or_test: and_test ("or" and_test)*
?and_test: not_test_ ("and" not_test_)*
?not_test_: "not" not_test_ -> not_test
          | comparison
          | _atom
comparison: _atom comp_op _atom
comp_op: COMPARISON_OP



# function calling

func_call: reference "(" [arguments] ")"
arguments: _expr ("," _expr)*

_atom: func_call
     | _literal
     | reference
     | "(" _expr ")"

# not used in grammar, but may appear in "node" passed from Parser to Compiler
encoding_decl: name

number: DEC_NUMBER | HEX_NUMBER | BIN_NUMBER | OCT_NUMBER | FLOAT_NUMBER | IMAG_NUMBER
string: STRING
boolean: CONST_FALSE | CONST_TRUE

# Other terminals

_NEWLINE: ( /\r?\n[\t ]*/ | COMMENT )+

%ignore /[\t \f]+/  // WS
%ignore /\\[\t \f]*\r?\n/   // LINE_CONT
%ignore COMMENT
%declare _INDENT _DEDENT


# Python terminals

!name: NAME
NAME: /[^\W\d]\w*/
COMMENT: /#[^\n]*/
CONST_TRUE: "True"
CONST_FALSE: "False"
COMPARISON_OP: ">" | "<" | "<=" | ">=" | "==" | "!="

STRING: /("(?!"").*?(?<!\\)(\\\\)*?"|'(?!'').*?(?<!\\)(\\\\)*?')/i

_SPECIAL_DEC: "0".."9"        ("_"?  "0".."9"                       )*
DEC_NUMBER:   "1".."9"        ("_"?  "0".."9"                       )*
          |   "0"             ("_"?  "0"                            )* /(?![1-9])/
HEX_NUMBER.2: "0" ("x" | "X") ("_"? ("0".."9" | "a".."f" | "A".."F"))+
OCT_NUMBER.2: "0" ("o" | "O") ("_"?  "0".."7"                       )+
BIN_NUMBER.2: "0" ("b" | "B") ("_"?  "0".."1"                       )+

_EXP: ("e"|"E") ["+" | "-"] _SPECIAL_DEC
DECIMAL: "." _SPECIAL_DEC | _SPECIAL_DEC "." _SPECIAL_DEC?
FLOAT_NUMBER.2: _SPECIAL_DEC _EXP | DECIMAL _EXP?
IMAG_NUMBER.2: (_SPECIAL_DEC      | FLOAT_NUMBER) ("J" | "j")