name: Spell checking
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request_target:
    branches:
      - "**"
    tags-ignore:
      - "**"
    types: ['opened', 'reopened', 'synchronize']

jobs:
  spelling:
    name: Spell checking
    permissions:
      contents: read
      pull-requests: read
      actions: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-24.04
    if: ${{ contains(github.event_name, 'pull_request') || github.event_name == 'push' }}
    steps:
    - name: check-spelling
      id: spelling
      uses: check-spelling/check-spelling@v0.0.24
      with:
        suppress_push_for_open_pull_request: 1
        checkout: true
        post_comment: 0
        check_extra_dictionaries: ''
        dictionary_source_prefixes: >
          {
          "cspell": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20241114/dictionaries/"
          }
        extra_dictionaries: |
          cspell:filetypes/filetypes.txt
          cspell:python/python.txt
          cspell:python/python/python-lib.txt
          cspell:python/python/python.txt
          cspell:python/common/extra.txt
          cspell:django/django.txt
          cspell:html/html.txt
          cspell:fullstack/fullstack.txt
          cspell:software-terms/softwareTerms.txt
          cspell:cpp/stdlib-c.txt
          cspell:cpp/stdlib-cpp.txt
          cspell:mnemonics/mnemonics.txt
          cspell:cpp/ecosystem.txt

